---
title: "Assignment"
description: |
  A short description of the post.
author:
  - name: Qinyu Wang
    url: https://www.linkedin.com/in/qinyu-wang/
date: 07-14-2021
output:
  distill::distill_article:
    distill::distill_article:
    toc: true
    toc_float: true
    self_contained: false
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.retina = 3,
                      eval = TRUE,
                      message = FALSE,
                      warning = FALSE)
```



# Library Packages
```{r}
packages = c('raster', 'sf', 
             'tmap', 'clock', 
             'tidyverse','ggplot2','ggraph',
             'lubridate','ggthemes','viridis','plotly','treemapify')
for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p,character.only = T)
}
```

# Import data
```{r}
cc_data<- read.csv('D:/ISSS608 Data Visualization/MC2/MC2/cc_data.csv')

loyalty_data <- read.csv('D:/ISSS608 Data Visualization/MC2/MC2/loyalty_data.csv')

car <- read_csv('D:/ISSS608 Data Visualization/MC2/MC2/gps.csv')
```

# Data parperation-cc_data
```{r}
cc_data_wkday <- cc_data

cc_data_wkday$dmy_hm <- date_time_parse(cc_data_wkday$timestamp,
                zone = "",
                format = "%m/%d/%Y %H:%M")

cc_data_wkday$weekday <- wday(cc_data_wkday$dmy_hm, 
                             label = TRUE, 
                             abbr = FALSE)

cc_data_wkday$hour <- hour(cc_data_wkday$dmy_hm)

cc_data_wkday$day <- day(cc_data_wkday$dmy_hm)

cc_data$last4ccnum <- as.character(cc_data$last4ccnum)

breaks <- hour(hm("00:00", "5:00", "12:00", "18:00", "23:59"))
labels <- c("Night", "Morning", "Afternoon", "Evening")

cc_data_wkday$dmy_hm <- cut(x=hour(cc_data_wkday$dmy_hm), breaks = breaks, labels = labels, include.lowest=TRUE)

```

#data parperation loyalty_data
```{r}
loyalty_card <- loyalty_data

loyalty_card$dmy<- date_time_parse(loyalty_card$timestamp,
                zone = "",
                format = "%m/%d/%Y")

loyalty_card$weekday <- wday(loyalty_card$dmy, 
                             label = TRUE, 
                             abbr = FALSE)

loyalty_card$day <- day(loyalty_card$dmy)

```

#data parperation car_data
```{r}
car$dmy_hm <- date_time_parse(car$Timestamp,
                zone = "",
                format = "%m/%d/%Y %H:%M:%S")

car$day <- day(car$dmy_hm)

car$hour <- hour(car$dmy_hm)

```


# the most popular locations
## Bar chart cc_data
```{r}
cc_bar_chart <- cc_data_wkday %>% 
  group_by(location) %>% 
  summarise(n = n()) %>% 
  ungroup()

p <- ggplot(cc_bar_chart,aes(x = reorder(location,-n), 
                             y = n)) + 
  geom_col(color="black", 
           fill="light blue") + 
  theme(axis.text.x = element_text(angle = 90, 
                                   hjust = 1, 
                                   vjust = .5))

p <- p + ggtitle("Location by frequen cc") + 
        labs(y="Frequency", x = "Location")

ggplotly(p)

```

## treemap cc_data
```{r}
cc_treemap <- cc_data_wkday %>% 
  select(location,price) %>% 
  group_by(location) %>% 
  mutate(total_price = sum(price)) %>% 
  ungroup()
  


sum_cc_data <- cc_data %>%
select(location, price) %>%
group_by(location) %>%
summarise(total_price = sum(price), total_count = n()) %>%
arrange(desc(total_count), desc(total_price))

glimpse(sum_cc_data)






ggplot(G20, aes(area = gdp_mil_usd, fill = hdi, label = country)) +
  geom_treemap() +
  geom_treemap_text(fontface = "italic", colour = "white", place = "centre",
                    grow = TRUE)

  



```



## Bar chart loyalty_data
```{r}
loyalty_bar_chart <- loyalty_data %>% 
  group_by(location) %>% 
  summarise(n = n()) %>% 
  ungroup()

p2 <- ggplot(loyalty_bar_chart,aes(x = reorder(location,-n), 
                             y = n)) + 
  geom_col(color="black", 
           fill="light blue") + 
  theme(axis.text.x = element_text(angle = 90, 
                                   hjust = 1, 
                                   vjust = .5))

p2 <- p2 + ggtitle("Location by frequency loyalty") + 
        labs(y="Frequency", x = "Location")

ggplotly(p2)

```

## Price_cc_card
```{r}
price <- cc_data %>%
  group_by(location) %>% 
  mutate(total_price = sum(price)) %>% 
    arrange(desc(total_price)) %>% 
distinct(location,.keep_all = TRUE)

ggplot(price,aes(x = location, y = total_price)) + 
  geom_col() 
```



# - when they are popular?
## Heatmap by weekday
```{r}
plot <- cc_data_wkday %>% 
  group_by(location,weekday,hour,) %>% 
  summarise(n = n()) %>% 
  ungroup() 

full_df <- expand.grid(location = unique(cc_data_wkday$location),
                       weekday = unique(cc_data_wkday$weekday),
                       hour = c(1:23))

plot_full <- plot %>% 
  right_join(
    full_df,
    by = c('location','weekday','hour') 
  ) %>% 
  mutate(hour = as.ordered(hour)) %>% 
  replace_na(list(n = 0L)) %>% 
  filter(location %in% c('Katerina’s Café'))


pwk<- ggplot(plot_full, aes(hour, weekday, fill = n)) + 
geom_tile(color = 'white',size = 0.1) + 
  facet_grid(~location) +
   scale_fill_distiller(palette = "Reds",direction = 1)
```
  
## Heatmap by date
```{r}
plot_day <- cc_data_wkday %>% 
  group_by(location,day,hour,) %>% 
  summarise(n = n()) %>% 
  ungroup() 

full_df_day <- expand.grid(location = unique(cc_data_wkday$location),
                       day = unique(cc_data_wkday$day),
                       hour = c(1:23))

plot_full_day <- plot_day %>% 
  right_join(
    full_df_day,
    by = c('location','day','hour') 
  ) %>% 
  mutate(hour = as.ordered(hour)) %>% 
  mutate(day = as.ordered(day)) %>% 
  replace_na(list(n = 0L)) %>% 
  filter(location %in% c('Katerina’s Café'))


pd <- ggplot(plot_full_day, aes(hour, day, fill = n)) + 
geom_tile(color = 'white',size = 0.1) + 
  facet_grid(~location) +
   scale_fill_distiller(palette = "Reds",direction = 1)

pd
```

## Heatmap car
```{r}
car_data <- car %>% 
  group_by(day,hour) %>% 
  summarise(n = n()) %>% 
  ungroup() 

full_df_car <- expand.grid(day = unique(car$day),
                          hour = c(1:23))

plot_full_car <- car_data %>% 
  right_join(
    full_df_car,
    by = c('day','hour') 
  ) %>% 
  mutate(hour = as.ordered(hour)) %>% 
  mutate(day = as.ordered(day)) %>% 
  replace_na(list(n = 0L)) 

ggplot(plot_full_car, aes(hour,day,fill = n)) + 
geom_tile(color = 'white',size = 0.1) + 
   scale_fill_distiller(palette = "Reds",direction = 1)

```